<form action="<?= $this->url('user', ['action' => 'login']) ?>" method="post">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" name="email" id="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="email">Password</label>
        <input type="text" name="email" id="email" class="form-control">
    </div>
    <div class="btn btn-default">Login</div>
</form>