<form action="<?= $this->url('user', ['action' => 'register']) ?>" method="post">
    <div class="form-group">
        <label for="email">Email</label>
        <input type="text" value="<?= $this->email ?>" name="email" id="email" class="form-control">
    </div>
    <div class="form-group">
        <label for="nick">Nick</label>
        <input type="text" name="nick" id="nick" class="form-control">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="text" name="password" id="password" class="form-control">
    </div>
    <button class="btn btn-default">Register</button>
</form>